apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sub
  labels:
    app: sub
    version: 1.0.0
    release: sub
spec:
  selector:
    matchLabels:
      app: sub
      version: 1.0.0
      release: sub
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: sub
        version: 1.0.0
        release: sub
    spec:
      containers:
      - name: sub
        image: fengyuanyang/mqttgo
        imagePullPolicy: Always
        command: [ "go" ]
        args: [ "run", "/go/src/mqtt/mqttSub.go" ]
        ports:
        - containerPort: 8080